### ISSUE TITLE
Download Links Broken

### ISSUE THREAD

**Issue by ginward** [ratschlab/GP-VAE#1]
It looks like that the following download links are broken: 

`hmnist`:
`https://www.dropbox.com/s/aidkzh525mvwf44/hmnist_mnar.npz?dl=1`

`sprites`
`https://www.dropbox.com/s/cjuzj71v5sgwcge/sprites.npz?dl=1`

**Comment by dbaranchuk** [comment]
Hi,

Indeed, I've accidentally deleted these files from dropbox. I'll update the links as soon as the data is loaded again.

Thanks for your report!
